#write a program to print the patterns given
print ("     *    ")
print ("  *     * ")
print ("*    *    *")
print ("  *     * ")
print ("     *    ")
print ("1")
print ("1  2")
print ("1  2  3")
print ("1  2  3  4") 
