#page 373 11.1 & 11.2
t1=eval(input("input 1: "))
t2=eval(input("input 2: "))
t3=eval(input("input 3: "))
print("type 1: ",type(t1))
print("type 2: ",type(t2))
print("type 3: ",type(t3))
print("tuple : ",tuple(t1))
print("tuple : ",tuple(t2))
print("tuple : ",tuple(t3))
